// 引入primeNg的所有模块
import { NgModule } from '@angular/core';
import { AccordionModule, AutoCompleteModule, BreadcrumbModule, ButtonModule, CalendarModule, CarouselModule, ChartModule, CheckboxModule, ChipsModule, CodeHighlighterModule, ConfirmDialogModule, ContextMenuModule, DialogModule, DragDropModule, DropdownModule, EditorModule, FieldsetModule, FileUploadModule, GalleriaModule, GMapModule, InputMaskModule, InputSwitchModule, InputTextareaModule, InputTextModule, LightboxModule, ListboxModule, MegaMenuModule, MenubarModule, MenuModule, MessagesModule, MultiSelectModule, OrderListModule, OverlayPanelModule, PaginatorModule, PanelMenuModule, PanelModule, PasswordModule, PickListModule, ProgressBarModule, RadioButtonModule, RatingModule, SelectButtonModule, SharedModule, SlideMenuModule, SliderModule, SpinnerModule, SplitButtonModule, StepsModule, TabMenuModule, TabViewModule, TerminalModule, TieredMenuModule, ToggleButtonModule, ToolbarModule, TooltipModule, TreeModule, TreeTableModule } from 'primeng';

@NgModule({
  exports: [
    PanelModule,
    InputTextModule,
    PasswordModule,
    ButtonModule,
    DialogModule,
    DropdownModule,
    TreeModule,
    SplitButtonModule,
    ConfirmDialogModule,
    PickListModule,
    MultiSelectModule,
    CalendarModule,
    StepsModule,
    AccordionModule,
    AutoCompleteModule,
    BreadcrumbModule,
    CarouselModule,
    ChartModule,
    CheckboxModule,
    ChipsModule,
    CodeHighlighterModule,
    SharedModule,
    ContextMenuModule,
    DragDropModule,
    EditorModule,
    FieldsetModule,
    FileUploadModule,
    GalleriaModule,
    GMapModule,
    InputMaskModule,
    InputSwitchModule,
    InputTextareaModule,
    LightboxModule,
    ListboxModule,
    MegaMenuModule,
    MenuModule,
    MenubarModule,
    MessagesModule,
    OrderListModule,
    OverlayPanelModule,
    PaginatorModule,
    PanelMenuModule,
    ProgressBarModule,
    RadioButtonModule,
    RatingModule,
    SelectButtonModule,
    SlideMenuModule,
    SliderModule,
    SpinnerModule,
    TabMenuModule,
    TabViewModule,
    TerminalModule,
    TieredMenuModule,
    ToggleButtonModule,
    ToolbarModule,
    TooltipModule,
    TreeTableModule,
  ],
})

export class PrimeNgModule { }
